services:

  core-deps:
    build:
      context: core
      target: deps

  core:
    build: core
    depends_on:
      - design-system
      - core-deps

  design-system:
    build: design-system
    ports:
      - 7824:5173

  coverage:
    build: coverage
    depends_on:
      - core
    ports:
      - 7823:80

  db:
    image: mariadb
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_RANDOM_ROOT_PASSWORD: yes

  back-deps:
    build:
      context: back
      target: deps

  back:
    build: back
    depends_on:
      - core
      - db
      - back-deps
    ports:
      - 7822:3000
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      ROLE_SIGN_PASSPHRASE: ${ROLE_SIGN_PASSPHRASE}
      ROLE_SIGN_SALT: ${ROLE_SIGN_SALT}
      VITE_WEBSOCKET_PROTOCOL: ${VITE_WEBSOCKET_PROTOCOL}
    restart: always

  front-deps:
    build:
      context: front
      target: deps

  front:
    build:
      context: front
      args:
        VITE_BACK_DOMAIN: ${VITE_BACK_DOMAIN}
        VITE_WEBSOCKET_PROTOCOL: ${VITE_WEBSOCKET_PROTOCOL}
    environment:
      VITE_BACK_DOMAIN: ${VITE_BACK_DOMAIN}
      VITE_WEBSOCKET_PROTOCOL: ${VITE_WEBSOCKET_PROTOCOL}
    depends_on:
      - core
      - back
      - front-deps
    ports:
      - 7825:5173